name: Deploy to Hosting
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install PHP dependencies
        run: |
          composer install --dev --optimize-autoloader

      - name: Upload via SFTP
        uses: pressidium/lftp-deploy-action@v1
        with:
          host: 92.53.96.37
          username: cg22164
          password: ${{ secrets.SFTP_PASSWORD }}
          server-dir: tkt-test/public_html/
